### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by angerhang**
See https://github.com/brucemiller/LaTeXML/pull/731 for details.

### CODE REVIEW

**Comment by kohlhase** [comment]
@dginev would you have a look at this and pull if you like it? 
This would solve issue https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/20 for us (I hope).

**Comment by dginev** [comment]
Two comments:
 * Bruce has a somewhat intricate handling of CommaList, so I would prefer for him to take a look
 * This PR is generic enough to benefit the main latexml repository
 * I had mentioned before via email that the KWARC fork of latexml is too far diverged, and can't be easily  realigned with the master repository. I would suggest experimenting with the master repo, especially since a naive installation of the stex plugin would be fetching Bruce's master and not the kwarc fork.

**Comment by dginev** [comment]
Bruce merged it, so we can reciprocate here.

Btw, my warning about trying to move away from the KWARC/LaTeXML fork is still active, since we're missing out on any new features added by Bruce in the main repo.

**Comment by kohlhase** [comment]
thanks for merging.

**Comment by kohlhase** [comment]
> I had mentioned before via email that the KWARC fork of latexml is too far diverged, and can't be easily realigned with the master repository. I would suggest experimenting with the master repo, especially since a naive installation of the stex plugin would be fetching Bruce's master and not the kwarc fork.

@dginev I am not sure I understand what you are saying. I interpret this as 
1. try to run sTeX with the LaTeXML master instead of with the KWARC branch and see what breaks. 
whereas I had earlier understood
2. I will (when I have time) have a look and see what I have to merge into master to get sTeX going. 

I see agree that 1. is probably more reasonable than 2. So I guess @angerhang should start doing that. Will you be able to supervise this?

**Comment by kohlhase** [comment]
Maybe we can skype about this (and your thesis and AITP) soon?

**Comment by dginev** [comment]
I am available for a skype session whenever. The KWARC/LaTeXML fork has diverged too far, I had spent 90 minutes trying to reintegrate it over a month ago, to no avail.

**Comment by kohlhase** [comment]
> I am available for a skype session whenever.

now you seem offline :-). I have time e.g. now

**Comment by kohlhase** [comment]
Yes, I am all for dropping the KWARC branch, but the question to me is how.

**Pull request merged**
